object users {
id
name
lastname
birthday
remoteId
}

object uvUser {
    userAverage
    uvMark
    uvComment
}


enum location{
DEPARTMENT
FACULTY
UNIVERSITY
}

object uvs {
id
remoteId
name
description
minSemester
isAvailableForCard
chs
}

object studyPlans {
id

}

object options {
name

}

object semesters {
    id
    number
}

object carts {
}

object uvTypes {
id
type
hoursByCredit
}

uvs "*" -- "*" uvs : uvCorequisite
uvs "*" -- "*" uvs : uvPrerequisite

uvUser "*" -- "1" users : user
uvUser  "*" -- "1" uvs : uv

users "0,1" -- "*" studyPlans
studyPlans "*" -- "0,1" options
options "0,1" -- "*" uvs : option
studyPlans "1" -- "*" semesters
semesters "*" -- "*" uvs
carts "0,1" -- "*" semesters
carts "*" -- "*" uvs

uvs "*" -- "1" uvTypes : type

uvs "*" -- "1" location : location

@enduml