spring:
  profiles: default
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/advisorapp
    username: root
    password:root
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update

server:
  port: 8090

security:
  basic:
    enabled: false

management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

project:
  name: advisorapp-api
  version: 0.1
  description: advisorapp default description

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

privateKey: "9g4LrPHpdpcjQ33KFTHJWjAsuPGa8yaKTS8YFJLEa5tQjfdMzDrxLsDyRA7tYmbBr9E66ppbMcLQXRccq7RYVBHEm5mwDHtnSHLt"
salt: "$2a$10$4/ln1/Ue6fCAaYmxukEvH."

---

spring:
  profiles: production
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:1664/advisorapp
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update

server:
  port: 8090

security:
  basic:
    enabled: false

privateKey: "53026072618764933cee4f10b559047cccbba4fc1cee4f10b5590NANOULEBGDU4447cccbba4fc1530260726187649"
salt: "$2a$10$xhBhvrl/hpu0HaLIYNQmcO"

---

spring:
  profiles: test
