### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring:
  profiles: default
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/advisorapp
    username: root
    password: null
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update

server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: advisorapp-api
  version: 0.1
  description: advisorapp default description

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

privateKey: "9g4LrPHpdpcjQ33KFTHJWjAsuPGa8yaKTS8YFJLEa5tQjfdMzDrxLsDyRA7tYmbBr9E66ppbMcLQXRccq7RYVBHEm5mwDHtnSHLt"
salt: "$2a$10$4/ln1/Ue6fCAaYmxukEvH."

---

spring:
  profiles: production
  datasource:
    url: jdbc:mysql://127.0.0.1:1664/advisorapp

---

spring:
  profiles: test
